# Generated by Django 6.0.1 on 2026-01-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_admission_number_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admission_number',
            field=models.CharField(blank=True, default='', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='staff_id',
            field=models.CharField(blank=True, default='', max_length=20, null=True, unique=True),
        ),
    ]
