# Generated by Django 6.0.1 on 2026-01-15 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_studentprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
