# Generated by Django 6.0.1 on 2026-01-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_schoolclass_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='reason',
            field=models.TextField(blank=True, help_text='Reason for absence (required if absent)', null=True),
        ),
    ]
